package models.customer.conditions;

public enum UserStates {
    USER_CONNECTED,

    QUICK_PRINT,
    QUICK_PRINT_DESCRIPTION,
    SELECT_SIZE_COLOR,
    UPLOADING_FILES,
    ONE_MORE_FILE,
    SEND_ORDER,
    ORDER_COMPLETE,
    INVALID_CHOICE,
    ERROR,

    CALC_PRODUCT,
    CHOOSE_PRODUCT,
    STIKERS,
    CARDS,
    BIZ_CARDS,
    FLYERS,

    INVALID_FILE;
}
