package models.users.conditions;

public enum UserStates {
    USER_CONNECTED,
    QUICK_PRINT_DESCRIPTION,
    QUICK_PRINT,
    SELECT_SIZE_COLOR,
    UPLOADING_FILES,
    ONE_MORE_FILE,
    SEND_ORDER,
    ORDER_COMPLETE,
    INVALID_CHOICE,
    ERROR,
    CALC_PRODUCT,
    INVALID_FILE;
}
